{% set VERSION = '3.0.0' %}
{% set EPICS = '3.14.12.6' %}

package:
  name: pyca
  version: {{ VERSION }}

source:
  path: ..

build:
  number: 1
  string: py{{ py }}np{{ np }}epics{{ EPICS }}

requirements:
  build:
    - python {{ PY_VER }}*
    - setuptools
    - epics-base {{ EPICS }}*
    - numpy {{ NPY_VER }}*

  run:
    - python {{ PY_VER }}*
    - epics-base {{ EPICS }}*
    - numpy {{ NPY_VER }}*

tests:
  import:
    pyca

about:
  home: https://github.com/slaclab/pyca
  licence: SLAC Open Licence
  summary: Python Channel Access
