{% set data = load_setup_py_data() %}
{% set EPICS = '3.14.12.6' %}

package:
  name: pyca
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 1
  string: py{{ py }}np{{ np }}epics{{ EPICS }}

requirements:
  build:
    - python {{ PY_VER }}*
    - setuptools
    - epics-base {{ EPICS }}*
    - numpy {{ NPY_VER }}*

  run:
    - python {{ PY_VER }}*
    - epics-base {{ EPICS }}*
    - numpy {{ NPY_VER }}*

test:
  imports:
    - pyca
    - psp

about:
  home: https://github.com/slaclab/pyca
  licence: SLAC Open Licence
  summary: Python Channel Access
